const AllImages = {
  logo: require("../assets/images/logo.svg").default,
  whiteLogo: require("../assets/images/logo-white.svg").default,
  person: require("../assets/images/person.svg").default,
  whitePerson: require("../assets/images/person-white.svg").default,
  authBackground: require("../assets/images/auth-bg.jpg"),
  user: require("../assets/images/user.png"),
  users: require("../assets/images/users.svg").default,
  hero: require("../assets/images/Hero-2-1.png"),
  greater: require("../assets/images/grater.svg").default,
  planeFilled: require("../assets/images/plane-filled.svg").default,
  departure: require("../assets/images/plane-departure.svg").default,
  swap: require("../assets/images/swap.svg").default,
  arrival: require("../assets/images/plane-arrival.svg").default,
  userLogo: require("../assets/images/heroicons-user.svg").default,
  calendar: require("../assets/images/calendar.svg").default,
  map: require("../assets/images/map.svg").default,
  man: require("../assets/images/man.png"),
  search: require("../assets/images/search.svg").default,
  plus: require("../assets/images/plus.svg").default,
  minus: require("../assets/images/minus.svg").default,
  flightBackground: require("../assets/images/list-bg.jpg"),
  browseFiles: require("../assets/images/browse-files.png"),
  Ornament2: require("../assets/images/Ornament-2.png"),
  Ornament69: require("../assets/images/Ornament-69.png"),
  animation: require("../assets/images/animation.gif"),
};
export default AllImages;
