const AllImages = {
  logo: require("../assets/images/logo.png"),
  whiteLogo: require("../assets/images/logo-white.png"),
  person: require("../assets/images/person.png"),
  whitePerson: require("../assets/images/person-white.png"),
  authBackground: require("../assets/images/auth-bg.jpg"),
  user: require("../assets/images/user.png"),
  users: require("../assets/images/users.png"),
  hero: require("../assets/images/Hero-2-1.png"),
  grater: require("../assets/images/grater.png"),
  planeFilled: require("../assets/images/plane-filled.png"),
  departure: require("../assets/images/plane-departure.png"),
  swap: require("../assets/images/swap-horiz.png"),
  arrival: require("../assets/images/plane-arrival.png"),
  userLogo: require("../assets/images/heroicons-user.png"),
  calendar: require("../assets/images/calendar.png"),
  map: require("../assets/images/map.png"),
  man: require("../assets/images/man.png"),
  search: require("../assets/images/search.png"),
  plus: require("../assets/images/plus.png"),
  minus: require("../assets/images/minus.png"),
  flightBackground: require("../assets/images/list-bg.jpg"),
  browseFiles: require("../assets/images/browse-files.png"),
  frame: require("../assets/images/Frame.png"),
  Ornament2: require("../assets/images/Ornament-2.png"),
  Ornament69: require("../assets/images/Ornament-69.png"),
  animation: require("../assets/images/animation.gif"),
};
export default AllImages;
